/*Lab 4, Exercise 2 (Lottery), CSCI 1101
Lottery.java has 3 instance variables; one holds the numbers generated by the computer,
another holds the numbers selected by user, and other is used to hold the number of matches.
It has a constructor which generates the random numbers. It has accessor/mutator methods to 
get and set the instance variables. It has a methods to add numbers to the userArray, find the
number of matches between userArray and lotteryNumbers, and a method that decides what to
depending on how many matches there are.
July 3rd, 2015
Liam Gowan B00673126
This is entirely my own work.
*/
public class Lottery{
   //instance variables
   private int[] lotteryNumbers = new int[5];
   private int[] userArray = new int[5];
   private int matches = 0;
   //constructor
   public Lottery(){//makes Lottery object
      for(int i=0; i<5; i++){//assigns 5 random numbers
         lotteryNumbers[i] = (int)(Math.random()*9+1);
      }
   }
   public void userArrayMaker(int[] userNum){//assigns 5 numbers selected by user to userArray
      for(int i = 0; i<5; i++){
         userArray[i] = userNum[i];
      }
   }
   public void matches(){//checks to see if there are matches
      for(int i=0; i<5; i++){
         if(lotteryNumbers[i] == userArray[i])
            matches++;
      }
   }
   public void printPrize(){
      //prints lotteryNumbers array picked by computer
      System.out.print("Lottery numbers picked by computer: ");
      for(int i=0; i<5; i++)
         System.out.print(lotteryNumbers[i] + " ");
      //prints userArray
      System.out.print("\nNumbers picked by user: ");
      for(int i=0; i<5; i++)
         System.out.print(userArray[i] + " ");
      //the following block of code will print how much the user wins depending on matches
      if(matches == 5)
         System.out.print("\nYou win the grand prize of ONE MILLION DOLLARS!");
      else if(matches == 4)
         System.out.print("\nYou win $500 000");
      else if(matches == 3)
         System.out.print("\nYou win $1000");
      else if(matches == 2)
         System.out.print("\nYou win $10");
      else if(matches == 1)
         System.out.print("\nYou win $2");
      else
         System.out.print("\nSorry, nothing for you.");   
   }
      
}